166 bugprofile mismatch in extension
onflow/FRW-Extension pull request #173
Opened 2024-11-14 10:24 UTC by zzggo

2024-11-14 11:26 UTC, tombeckenham commented on src/ui/views/Dashboard/Header.tsx
> +
Why are you no longer setting the current wallet here?

2024-11-14 11:41 UTC, zzggo commented on src/ui/views/Dashboard/Header.tsx
> +
I actually only need to set the walletinfo in the background, the component state will be refresh after the reload.

2024-11-14 22:44 UTC, tombeckenham requested changes
I just had one comment to put a try catch around the function that sets setSwitchLoading. I've made a lot of changes to Header.tsx to update linting problems.

2024-11-15 03:39 UTC, tombeckenham approved these changes

2024-11-15 03:39 UTC, tombeckenham commented on src/ui/views/Dashboard/Header.tsx
> +    setSwitchLoading(true);
This should have a try catch finally around the statements in this function so that setSwitchLoading(false) is always called

2024-11-15 03:39 UTC, tombeckenham approved these changes

2024-11-15 03:40 UTC, tombeckenham approved these changes

2024-11-15 06:01 UTC, merged